# Generated by Django 4.2.11 on 2024-03-15 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_id', models.CharField(max_length=100)),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_address', models.TextField()),
                ('date_deployed', models.DateField()),
                ('last_transaction', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('retrieved', models.BooleanField(default=False)),
                ('date_retrieved', models.DateField()),
                ('faulty', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('serialnumber', models.TextField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('connectivity', models.CharField(max_length=100)),
                ('sim', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('settlement_account', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitor_id', models.CharField(max_length=100)),
                ('monitor_name', models.CharField(max_length=100)),
                ('monitor_address', models.TextField()),
                ('zone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('town', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(max_length=100)),
                ('terminal_name', models.CharField(max_length=100)),
                ('terminal_address', models.TextField()),
                ('pos_id', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('device_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deviceinfo')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.terminallocation')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.merchant')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.monitor')),
            ],
        ),
        migrations.AddField(
            model_name='monitor',
            name='relationship_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relationshipmanager'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.merchantcontactperson'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='relationship_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relationshipmanager'),
        ),
        migrations.AddField(
            model_name='activity',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deviceinfo'),
        ),
    ]
