# Generated by Django 4.2.10 on 2024-04-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_terminal_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='terminal_id',
        ),
    ]
