# Generated by Django 4.2.10 on 2024-04-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_terminal_terminal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='pos_id',
        ),
    ]
