# Generated by Django 4.2.10 on 2024-04-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_terminal_pos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinfo',
            name='device_id',
        ),
    ]
