# Generated by Django 4.2.10 on 2024-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_monitor_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='zone',
            field=models.CharField(choices=[('zone 1', 'Zone 1'), ('zone 2', 'Zone 2'), ('zone 3', 'Zone 3')], default='zone1', max_length=20),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('faulty', 'Faulty'), ('retrieved', 'Retrieved'), ('deployed', 'Deployed')], default='inactive', max_length=20),
        ),
    ]
