# Generated by Django 4.2.10 on 2024-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_monitor_zone_alter_terminal_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='status',
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('faulty', 'Faulty'), ('retrieved', 'Retrieved'), ('deployed', 'Deployed')], default='inactive', max_length=20),
        ),
    ]
